### ISSUE TITLE
Add: nginx proxy and guid

### ISSUE THREAD

**Issue by DarkShyMW** [rslay/ZeroChat#52]
Hello, how i can to connect my domain to my website? I use cloudflare flexible SSL, and i need use domain name. How? If i use redirect, i take something strange - web is crashed when i try write message.
For example: https://hive.slainscraft.com/

**Comment by rslay** [comment]
@DarkShyMW 
I'm aware of this, added the solution to the README just now.
Screenshot for historical purposes:
![image](https://user-images.githubusercontent.com/25256438/119420016-73ab8100-bcc9-11eb-9240-75d84d00c8d3.png)

[An article](https://justhack.in/stateful-http#issues) I wrote on the HTTP streaming technique goes into the problem a little more in depth if you're curious why it happens.

**Comment by DarkShyMW** [comment]
@rslay oh. Thanks you <3
